try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("try except is finished")